chromium: Fix build with clang 12
OSSystems/meta-browser pull request #466
Opened 2021-03-10 07:30 UTC by kraj

Signed-off-by: Khem Raj <raj.khem@gmail.com>

2021-03-10 08:40 UTC, rakuco requested changes

2021-03-10 20:01 UTC, kraj commented on recipes-browser/chromium/files/limits.patch
> +Upstream-Status: Pending
done in v2

2021-03-10 22:34 UTC, rakuco approved these changes
lgtm!

2021-03-16 12:51 UTC, MastaG commented
Works for me.

2021-03-17 17:36 UTC, shr-project commented
```
ERROR: chromium-x11-89.0.4389.90-r0 do_patch: Fuzz detected:

Applying patch 0001-IWYU-include-limits-for-std-numeric_limits.patch
patching file third_party/perfetto/src/trace_processor/containers/string_pool.h
Hunk #1 succeeded at 23 with fuzz 1 (offset 1 line).


Applying patch 0001-IWYU-include-limits-for-std-numeric_limits-2.patch
patching file components/federated_learning/floc_constants.cc
Hunk #1 succeeded at 6 with fuzz 2 (offset 2 lines).


The context lines in the patches can be updated with devtool:

    devtool modify chromium-x11
    devtool finish --force-patch-refresh chromium-x11 <layer_path>

Don't forget to review changes done by devtool!

ERROR: chromium-x11-89.0.4389.90-r0 do_patch: QA Issue: Patch log indicates that patches do not apply cleanly. [patch-fuzz]
```

Needs small update for the new chromium version merged recently, will update locally.

2021-03-17 18:40 UTC, shr-project commented
The first 2 patches are already included in 89.0.4389.90 currently in master, the 3rd patch does apply cleanly, but it might not be needed as I've already built this with clang12 I believe and the only failure I've seen was gold segfaulting in 1 build (from 3 I did in https://github.com/shr-project/test-oe-build-time)
```
clang-12: error: unable to execute command: Segmentation fault
clang-12: error: linker command failed due to signal (use -v to see invocation)

dmesg:
[225501.270737] ld.gold[1812127]: segfault at 7f120948a08a ip 000055797f63e0b7 sp 00007f15ff869c40 error 4 in x86_64-linux-gnu-ld.gold[55797f55d000+197000]
```

2021-03-17 19:02 UTC, kraj commented
> The first 2 patches are already included in 89.0.4389.90 currently in master, the 3rd patch does apply cleanly, but it might not be needed as I've already built this with clang12 I believe and the only failure I've seen was gold segfaulting in 1 build (from 3 I did in https://github.com/shr-project/test-oe-build-time)
> 
> ```
> clang-12: error: unable to execute command: Segmentation fault
> clang-12: error: linker command failed due to signal (use -v to see invocation)
> 
> dmesg:
> [225501.270737] ld.gold[1812127]: segfault at 7f120948a08a ip 000055797f63e0b7 sp 00007f15ff869c40 error 4 in x86_64-linux-gnu-ld.gold[55797f55d000+197000]
> ```

third patch is needed when using gcc11 headers

2021-03-17 22:00 UTC, kraj commented
closing this one

2021-03-17 22:00 UTC, closed without merging