chromium: Do not use std::is_standard_layout in assert
OSSystems/meta-browser pull request #482
Opened 2021-03-20 03:23 UTC by kraj

This assert fails with GCC-11 runtime, so disable it as a workaround
reported upstream
https://bugs.chromium.org/p/chromium/issues/detail?id=1189788

Signed-off-by: Khem Raj <raj.khem@gmail.com>

2021-03-20 16:55 UTC, otavio requested changes

2021-03-20 16:55 UTC, otavio commented on meta-chromium/recipes-browser/chromium/files/0014-sql-Disable-is_standard_layout-assert.patch
> +
Please add the upstream status information and mentioned the bug report here so it can be referred when updating the recipe.

2021-03-20 17:07 UTC, otavio commented on meta-chromium/recipes-browser/chromium/files/0014-sql-Disable-is_standard_layout-assert.patch
> +
Shouldn't the referred bug report to be included in the commit log?

2021-03-20 17:12 UTC, kraj commented on meta-chromium/recipes-browser/chromium/files/0014-sql-Disable-is_standard_layout-assert.patch
> +
done

2021-03-20 17:27 UTC, otavio approved these changes

2021-03-21 20:24 UTC, rakuco commented
By GCC runtime do you mean libstdc++ or is this something else?

2021-03-21 21:18 UTC, kraj commented
> By GCC runtime do you mean libstdc++ or is this something else?
yes, but C++ compiler headers in this case particularly, I think all linux distros will run into this problem once they start
using gcc 11 and try to compile chromium.

2021-03-21 21:58 UTC, rakuco commented
Weren't we using libc++ in the build? I'm still trying to understand if it's the standard C++ library or some header that will always come from GCC regardless of compiler/standard library choice.

2021-03-22 01:35 UTC, kraj commented
> Weren't we using libc++ in the build? I'm still trying to understand if it's the standard C++ library or some header that will always come from GCC regardless of compiler/standard library choice.

as I mentioned these are compiler headers, if you are more curious look at the preprocessed files I have attached to
https://bugs.chromium.org/p/chromium/issues/detail?id=1189788
you will understand more.

2021-03-22 09:00 UTC, rakuco commented
OK, AFAICS the preprocessed file confirmed that it's libstdc++, which means we're not using libc++ as I thought we already were. I think we have 2 options: switch to libc++ or wait for a response from upstream for this issue, as I think removing this `static_assert()` call will make the code build but crash at runtime (based on what the assert is checking).

2021-03-22 18:33 UTC, kraj commented
> OK, AFAICS the preprocessed file confirmed that it's libstdc++, which means we're not using libc++ as I thought we already were. I think we have 2 options: switch to libc++ or wait for a response from upstream for this issue, as I think removing this `static_assert()` call will make the code build but crash at runtime (based on what the assert is checking).

yeah I think using libc++ is the right thing, although that means there are two options, user internal vendored version of libc++ which maybe out of sync with clang used to compile it. Or use `RUNTIME = "llvm"` in local.conf but that means now you are switching system defaults to use libc++ instead of libstdc++, I think option 1 is good.

2021-03-23 15:12 UTC, rakuco commented
By option 1 do you mean switching to Chromium's bundled libc++ and compiler_rt copy? If we go for the other option, isn't it safe to just set `RUNTIME` to "llvm" in `chromium.inc` like we do for `TOOLCHAIN = "clang"`?

2021-03-23 16:11 UTC, kraj commented
> By option 1 do you mean switching to Chromium's bundled libc++ and compiler_rt copy? If we go for the other option, isn't it safe to just set `RUNTIME` to "llvm" in `chromium.inc` like we do for `TOOLCHAIN = "clang"`?

hmm thats good option to make it at recipe level

2021-03-23 19:31 UTC, kraj commented
@rakuco I have switched chromium to use llvm runtime, and it fixes the problem I was observing.

2021-03-23 19:42 UTC, rakuco commented
I'm testing some builds with this setting here too. It's a big change, so my plan is to file an issue, get @msisov and others to test it too and then make the switch in another PR.

2021-03-23 20:59 UTC, kraj commented
> I'm testing some builds with this setting here too. It's a big change, so my plan is to file an issue, get @msisov and others to test it too and then make the switch in another PR.

OK sounds good. I will keep this around until then and close it after referring the future PR

2021-03-25 10:44 UTC, rakuco commented
> so my plan is to file an issue

#488, for the record.

2021-03-27 03:25 UTC, kraj commented
Please test this change together with https://github.com/OSSystems/meta-browser/pull/489 or wait for that PR to land in master.  if you don't have a lot of RAM otherwise you might see linker crashes which are not related to this change but to layer restructuring.

2021-03-30 16:17 UTC, yifan19 commented
> Please test this change together with #489 or wait for that PR to land in master. if you don't have a lot of RAM otherwise you might see linker crashes which are not related to this change but to layer restructuring.

as discussed recently #485, segfault can be seen even if you have around 126GB of RAM

2021-03-30 16:19 UTC, kraj commented
> > Please test this change together with #489 or wait for that PR to land in master. if you don't have a lot of RAM otherwise you might see linker crashes which are not related to this change but to layer restructuring.
> 
> as discussed recently #485, segfault can be seen even if you have around 126GB of RAM

hmm that means there is something going on with gold itself. I don't plan to debug it myself.

2021-03-31 15:14 UTC, rakuco commented
Replaced by #492.

2021-03-31 15:14 UTC, closed without merging