chromium: Add opengl to REQUIRED_DISTRO_FEATURES
OSSystems/meta-browser pull request #498
Opened 2021-04-14 00:45 UTC by yifan19

Chromium depends on virtual/libgl,
which oe-core provides by default in mesa.

opengl or vulkan is a REQUIRED_DISTRO_FEATURES for mesa.

In a minimal build of oe-core + meta-oe + meta-python2,
bitbake would complain that nothing provides
virtual/libgl, virtual/libgles2.

Also makes meta-chromium pass yocto-check-layer.

Signed-off-by: Yi Fan Yu <yifan.yu@windriver.com>

2021-04-14 11:54 UTC, otavio requested changes

2021-04-14 11:54 UTC, otavio commented on meta-chromium/recipes-browser/chromium/chromium-gn.inc
> +REQUIRED_DISTRO_FEATURES = "opengl"
This should be `opengl`OR `vulkan`, right?

2021-04-14 15:14 UTC, yifan19 commented on meta-chromium/recipes-browser/chromium/chromium-gn.inc
> +REQUIRED_DISTRO_FEATURES = "opengl"
sure that was the other alternative, following what mesa has.
I am not familiar with `vulkan`
will send v2

2021-04-14 19:16 UTC, yifan19 commented
`vulkan` doesn't provide egl in recipe mesa though

ERROR: Nothing PROVIDES 'virtual/egl' (but /yow-lpggp32/yyu1/yocto/openembedded-core/meta-browser/meta-chromium/recipes-browser/chromium/chromium-x11_89.0.4389.114.bb DEPENDS on or otherwise requires it). Close matches:
  virtual/kernel
  virtual/mesa
  virtual/perf
ERROR: Required build target 'chromium-x11' has no buildable providers.
Missing or unbuildable dependency chain was: ['chromium-x11', 'virtual/egl']

2021-04-15 18:25 UTC, yifan19 commented
it is buildable with vulkan if you remove PACKAGECONFIG `use-egl` and use `mesa-gl`

2021-04-19 16:26 UTC, yifan19 commented
@otavio  can this be merged, i used ANY_OF_DISTRO instead

2021-04-20 14:23 UTC, yifan19 commented
fixed commit log to  ANY_DISTRO_FEATURES

2021-04-20 14:29 UTC, otavio approved these changes

2021-04-20 14:29 UTC, merged