README: add meta-browser typical use case
OSSystems/meta-browser pull request #504
Opened 2021-04-28 09:21 UTC by kenhys

Adding a typical use case may help the user to understand it.

2021-04-28 11:24 UTC, otavio requested changes

2021-04-28 11:24 UTC, otavio commented on meta-chromium/README.md
> +  "
You can use `bitbake-layers` tool to do this without manually editing it.

2021-04-28 12:54 UTC, kenhys commented on meta-chromium/README.md
> +  "
Thanks, I've fixed to use bitbake-layers.

2021-04-28 12:57 UTC, otavio approved these changes

2021-04-28 13:06 UTC, rakuco reviewed
The instructions look mostly OK, but I'm still wondering if they are really necessary: isn't the process basically identical to any other layer, and thus already described in the OE or Yocto documentation?

2021-04-28 13:06 UTC, rakuco commented on meta-chromium/README.md
> +And, append target as I in conf/local.conf.
Sorry, I don't understand this sentence. What target are you appending where, and what does "as I" mean?

2021-04-28 13:06 UTC, rakuco commented on meta-chromium/README.md
> +The following steps are typical use case which builds chromium-ozone-wayland for example.
I think the most important part of the process for chromium-ozone-wayland is to set things like `DISTRO_FEATURES` appropriately so that Wayland's used instead of X11, but this is not mentioned here.

2021-04-28 13:15 UTC, kenhys commented on meta-chromium/README.md
> +And, append target as I in conf/local.conf.
Oops, I've removed garbage.

2021-04-28 13:45 UTC, shr-project commented
> The instructions look mostly OK, but I'm still wondering if they are really necessary: isn't the process basically identical to any other layer, and thus already described in the OE or Yocto documentation?

Agreed, also why should meta-browser recommend to use poky instead of checking out oe-core + bitbake separately.

The list of necessary layers is already included in LAYERDEPENDS (which shows reasonable error message when some are missing in your bblayers.conf) and "This layer depends on:" section above. Showing how to use git to clone them IMHO doesn't belong in meta-browser.

2021-04-28 13:47 UTC, shr-project commented on meta-chromium/README.md
> +```
This "typical" case will also cause chromium-ozone-wayland to be installed in various initramfs* images if you platform uses one, which is definitely not something you want.

Also trailing space isn't needed with _append, only the leading one is.

2021-06-17 13:11 UTC, rakuco commented
@kenhys Once again, thank you for writing the patch and submitting it. I think the consensus is that it is not necessary though, given it duplicates instructions available in existing documentation or which is output by the tools we have available, as explained above. Please feel free to reopen if you'd like to discuss it further.

2021-06-17 13:11 UTC, closed without merging

2021-06-18 02:06 UTC, kenhys commented
> I think the consensus is that it is not necessary though, 

it seems that it is reasonable.