chromium: add PACKAGECONFIG for gtk
OSSystems/meta-browser pull request #576
Opened 2021-10-10 19:13 UTC by MarkusVolk

Recently i found out, that chromium needs to be built with use_gtk=true if you want it to respect the gtk cursor theme.
This seems to be related to a change in use flags in chromium. There has been a use_gtk3 option that was true by
default. In addition we had use_gtk to enable builds with gtk+2.

Now it looks like we only have use_gtk to enable build with gtk+
https://github.com/chromium/chromium/blob/72ceeed2ebcd505b8d8205ed7354e862b871995e/build/config/linux/gtk/gtk.gni#L9

We have this disabled by default so i guess all current builds are without using gtk:
https://github.com/OSSystems/meta-browser/blob/8df26e66c28b43f1630fcd2cb952a1e69b6e6558/meta-chromium/recipes-browser/chromium/chromium-ozone-wayland_94.0.4606.71.bb#L30

Make gtk a PACKAGECONFIG to have an option.

Signed-off-by: MarkusVolk <f_l_k@t-online.de>

2021-10-11 06:23 UTC, msisov requested changes

2021-10-11 06:23 UTC, msisov commented on meta-chromium/recipes-browser/chromium/chromium-gn.inc
> +PACKAGECONFIG[gtk] = "use_gtk=true,use_gtk=false,gtk+3"
gtk used to be true by default on X11 builds.

2021-10-11 06:58 UTC, MarkusVolk commented on meta-chromium/recipes-browser/chromium/chromium-gn.inc
> +PACKAGECONFIG[gtk] = "use_gtk=true,use_gtk=false,gtk+3"
I did a test build for chromium-x11 on aarch64 yesterday and explicitly disabled gtk ... it completed without errors.
Seems like meanwhile using gtk is completely optional
Should i make gtk the default again like this?
`PACKAGECONFIG ??= "gtk upower use-egl"`
Should it be default for both, x11 and wayland builds?

2021-10-11 07:01 UTC, msisov commented on meta-chromium/recipes-browser/chromium/chromium-gn.inc
> +PACKAGECONFIG[gtk] = "use_gtk=true,use_gtk=false,gtk+3"
My expectation is that gtk is optional, but it is set by default on X11, but disabled on Wayland.

2021-10-11 07:43 UTC, MarkusVolk commented on meta-chromium/recipes-browser/chromium/chromium-gn.inc
> +PACKAGECONFIG[gtk] = "use_gtk=true,use_gtk=false,gtk+3"
Works like this. args.gn shows 'use_gtk = true' for chromium-x11

2021-10-15 13:43 UTC, MarkusVolk commented
my idea was to reflect the fact, that gtk+3 is not a hard dependency anymore and could be left out. This i thought could be useful for non gtk builds. I guess it would be also possible to run chromium under a qt environment ?

A second thing i thought about was, that it might come easier to handle gtk in the bridging time between gtk+3/gtk+4. We would just need to add the PACKAGECONFIG like this:

PACKAGECONFIG[gtk3] = "use_gtk=true,use_gtk=false,gtk+3"
PACKAGECONFIG[gtk4] = "use_gtk=true,use_gtk=false,gtk+4"

Anyway my personal motivation on this is quite low. It's also possible to just pass 'use_gtk=true' in a chromium-ozone-wayland.bbappend to fix the wayland gtk issue.
If you don't want to support building without gtk+ then your solution would be probably the most clean one and would bypass the  problem as well.

2021-10-30 17:08 UTC, MastaG commented
Perhaps a bit unrelated to this MR.
But what's the benefit of disabling GTK+ support?
For example isn't it required to get the native file-choser/picker when running it on Gnome Desktop?

2021-12-22 05:50 UTC, closed without merging