chromium: update to 112.0.5615.165
OSSystems/meta-browser pull request #709
Opened 2023-04-26 12:35 UTC by nrpt-m

2023-04-26 12:51 UTC, nrpt-m commented
@MaxIhlenfeldt, @rakuco,
After updating to 112.0.5615.165 , have successfully built for master branch and all systems worked well.
Have also built for dunfell branch & observed that build for all systems completed successfully except qemuarm64.

Have got this below error while building for qemuarm64:

> ERROR: chromium-x11-112.0.5615.165-r0 do_update_node_modules: Execution of '/buildarea/eng1/chromium/b/build-dunfell/tmp/work/aarch64-poky-linux/chromium-x11/112.0.5615.165-r0/temp/run.do_update_node_modules.3507160' failed with exit code 1
> | DEBUG: Executing shell function do_update_node_modules
> | npm WARN webui-node-modules@1.0.0 No repository field.
> | npm WARN webui-node-modules@1.0.0 No license field.
> | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
> | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> |
> | audited 258 packages in 7.306s
> |
> | 42 packages are looking for funding
> |   run `npm fund` for details
> |
> | found 0 vulnerabilities
> |
> | patching file index.d.ts
> | Reversed (or previously applied) patch detected!  Assume -R? [n]
> | Apply anyway? [n]
> | Skipping patch.
> | 1 out of 1 hunk ignored -- saving rejects to file index.d.ts.rej
> | WARNING: /buildarea/eng1/chromium/b/build-dunfell/tmp/work/aarch64-poky-linux/chromium-x11/112.0.5615.165-r0/temp/run.do_update_node_modules.3507160:1 exit 1 from 'patch -d node_modules/@types/d3/ -p1 < chromium_d3_types_index.patch'

2023-04-26 14:17 UTC, rakuco reviewed
Thanks for the update. The nodejs error sounds very weird and I'm not sure how to fix it yet.

In the meantime, could you just update the commit/PR message and include what's in #706 (i.e. the license changes and the rest), and mention @MaxIhlenfeldt and @kraj as contributors?

2023-04-26 14:49 UTC, kraj commented on meta-chromium/recipes-browser/chromium/files/fix-libc-version-include.patch
> +gnu/libc-version.h is only in glibc therefore guard it with __GLIBC__
I think it is generic the glibc specific bits are already ifdef’d but it’s fine if we want to make it musl specific infact it could be sent upstream for review

2023-04-26 14:57 UTC, rakuco commented on meta-chromium/recipes-browser/chromium/files/fix-libc-version-include.patch
> +gnu/libc-version.h is only in glibc therefore guard it with __GLIBC__
Since this is not breaking the generic, non-musl case, I'd rather keep this in a musl-specific location. It'd be great if you could send an upstream patch though.

2023-04-26 17:37 UTC, nrpt-m commented on meta-chromium/recipes-browser/chromium/chromium-gn.inc
> +do_update_node_modules () {
Added.

2023-04-27 19:08 UTC, kraj commented
> @rakuco , @MaxIhlenfeldt , Have also built & tested on kirkstone & mickledore branches and below were the observations. For kirkstone, all systems work well. On qemux86-64, have observed this below error in kernel log as well as in chromium execution logs but, chromium works fine.
> 
> > libGL error: pci id for fd 4: 1234:1111, driver (null)
> > ibGL error: MESA-LOADER: failed to open bochs-drm: /usr/lib/dri/bochs-drm_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/dri, suffix _dri)
> > libGL error: failed to load driver: bochs-drm
> 
> For mickledore, all systems work well except qemuarm. It is using the 6.1.25 kernel on qemuarm and we see the following error:
> 
> > vmap allocation for size 4100096 failed: use vmalloc= to increase size
> 

this is perhaps fixed with https://lists.openembedded.org/g/openembedded-core/message/180198

> System appears to boot well but, user-interface is not responding. Earlier, this issue was not observed with the use of Linux-yocto-dev kernel 6.3.0 version but now, with this kernel as well we observed same.

2023-04-27 19:09 UTC, kraj commented
> @rakuco , @MaxIhlenfeldt , Have also built & tested on kirkstone & mickledore branches and below were the observations. For kirkstone, all systems work well. On qemux86-64, have observed this below error in kernel log as well as in chromium execution logs but, chromium works fine.
> 
> > libGL error: pci id for fd 4: 1234:1111, driver (null)
> > ibGL error: MESA-LOADER: failed to open bochs-drm: /usr/lib/dri/bochs-drm_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/dri, suffix _dri)
> > libGL error: failed to load driver: bochs-drm

I think this is perhaps harmless.

> 
> For mickledore, all systems work well except qemuarm. It is using the 6.1.25 kernel on qemuarm and we see the following error:
> 
> > vmap allocation for size 4100096 failed: use vmalloc= to increase size
> 
> System appears to boot well but, user-interface is not responding. Earlier, this issue was not observed with the use of Linux-yocto-dev kernel 6.3.0 version but now, with this kernel as well we observed same.

2023-05-02 17:39 UTC, rwmacleod commented
@khem, I've asked Ross and Steve if the "machine/qemuarm*: don't explicitly set vmalloc " can / should be backported to mickledore.

@MaxIhlenfeldt   @nrpt-m  has seen two problems:
1. qeumarm64 build fails on dunfell. Can you reproduce that?
2. On dunfell, if you build once, it will succeed for qemuarm for example, then the qemuarm64 build failed and Narpat tried to build a second time for qemuarm, without doing a clean, that build failed as well. I suspect but we haven't yet confirmed that *any* second build will fail because the new stage added always attempt to re-apply the patches. Narpat to confirm.

More to come tomorrow.

2023-05-03 14:05 UTC, nrpt-m commented
> 2. On dunfell, if you build once, it will succeed for qemuarm for example, then the qemuarm64 build failed and Narpat tried to build a second time for qemuarm, without doing a clean, that build failed as well. I suspect but we haven't yet confirmed that _any_ second build will fail because the new stage added always attempt to re-apply the patches. Narpat to confirm.
> 
> More to come tomorrow.

Have confirmed that "_any_ second build is not failing" by building quemarm on dunfell 2-3 times & it completed without any error.

2023-05-03 15:24 UTC, kraj approved these changes
I think I am fine with this to go in.

2023-05-04 18:12 UTC, nrpt-m commented
@kraj I think we are close but, we can't access the network outside the fetch stage.
@rwmacleod and I concluded that rather then running npm after patching we could run npm once manually and then generated a patch & save it. Then, we can take @MaxIhlenfeldt patches along with our saved patch and apply them all during the do_patch stage.

We have done that by using npm from the host and unfortunately the patch is 44MB ! 
We are going to try using the version of npm that shipped with dunfell to see if it generates a smaller patch.

Does it seems like good idea ? Would the 44MB patch be acceptable ? Currently the meta-browser layer is 14MB.
[chromium-112.0.5615.165-dunfell-rollup-3.12.0-2.58.0-diffstat.txt](https://github.com/OSSystems/meta-browser/files/11400226/chromium-112.0.5615.165-dunfell-rollup-3.12.0-2.58.0-diffstat.txt)

2023-05-04 20:16 UTC, rwmacleod commented
@ekapllaj yes, one can but that's not a good idea and some OE users need to have the build system and all related source delivered to them so they can do offline builds. That seems kind of outrageous when you're building the chromium browser but those are the requirements that certain organizations have. Given that patching the source code is equivalent to running the 'npm install' command, I think the cost of the rather large 44 MB patch is worthwhile.

That said I do need to become more familiar with npm packaging in Yocto.  I acknowledged that the source for the rollup module is < 2 MB and that ideally, we'd figure out how to get npm to fetch from the local source caches rather than accessing the internet. We'd still need to do the fetch during the fetch stage.

2023-05-04 20:45 UTC, otavio commented
I would like to focus on discussing offline building further and exploring other options. The size of the 44MB patch is unreasonable, particularly considering that it will vary with each new release.

2023-05-04 21:29 UTC, rwmacleod commented
@otavio sounds good. 

I came to that conclusion about an hour after @nrpt-m  and I coughed up the 44 MB patch! ;-)

I'll continue to work on it with @nrpt-m  for an hour or two a day unless someone else picks up the ball full-time.
Some background is here: https://wiki.yoctoproject.org/wiki/TipsAndTricks/NPM
and the various commit logs and some YP documentation may even exist.

2023-05-05 09:36 UTC, MaxIhlenfeldt commented
Hi all, I still don't have a lot of time for this. I fear it might continue to be like this until W20 (i.e. still no time next week), sorry for that.

Regarding the NPM stuff, do we actually have to run NPM to replace the version of `rollup` used? Maybe it's enough to ship https://registry.npmjs.org/rollup/-/rollup-2.58.0.tgz, which is only 1.1 MB, and extract it over the existing dist? I have no idea if that might lead to any dependency problems, but it may be worth a try.

2023-05-05 10:43 UTC, rakuco commented
There's also the possibility of adding a new nodejs14 recipe to dunfell as discussed here: https://github.com/OSSystems/meta-browser/pull/706#issuecomment-1518890518

I'm not sure how much work that would be (i.e. how many different architectures need to be tested and what tests to run besides just building the recipe), but it would be the cleanest solution for us, as I expect Chromium to increasingly depend on new rollup features over time.

2023-05-05 10:53 UTC, MaxIhlenfeldt commented
That would be great of course. But I suppose it would take some time until that's usable, and we probably need a solution for the mean time?

2023-05-05 11:09 UTC, rakuco commented
@kraj could you give more details on what kind of testing would be needed for this recipe to be added? Looking at node 14's release notes I don't see many/any breaking changes, in the best case scenario copy-pasting the node recipe from a more recent branch would Just Work.

2023-05-08 18:02 UTC, nrpt-m commented
Hi all,
Have updated the nodejs_12.22.12 recipe to nodejs-native_14.18.1 and commented the "0017-Revert-WebUI-Update-Rollup-to-v3.12.0.patch" along with the workaround changes for dunfell in the chromium recipe.

With these above changes, we are able to build the qemux86-64 & rpi4 for dunfell without any error/issue. Now, the build is using nodejs-native_14.18.1, while building the chromium 112.0.5615.165 version. Will build the remaining systems and test.

@rwmacleod 
Please add, if I have missed anything.

2023-05-09 00:27 UTC, rwmacleod commented
@nrpt-m Good summary. We'll work on some PREFERRED_VERSION changes tomorrow ensure that nodejs_12 is the default for normal uses of meta-oe but that chromium requires and depends on nodejs-native_14.

2023-05-09 02:16 UTC, kraj commented
> Hi all, Have updated the nodejs_12.22.12 recipe to nodejs-native_14.18.1 and commented the "0017-Revert-WebUI-Update-Rollup-to-v3.12.0.patch" along with the workaround changes for dunfell in the chromium recipe.
> 
> With these above changes, we are able to build the qemux86-64 & rpi4 for dunfell without any error/issue. Now, the build is using nodejs-native_14.18.1, while building the chromium 112.0.5615.165 version. Will build the remaining systems and test.
> 
> @rwmacleod Please add, if I have missed anything.

Can you post the nodejs upgrade patch to dunfell mega-oe

2023-05-09 19:37 UTC, nrpt-m commented
@kraj , The patch is not quite ready.

@rwmacleod tells me that he is little rusty about PREFERRED_VERSION settings but, we tried making the following change:

meta-oe/conf/layer.conf
+PREFERRED_VERSION_nodejs ?= "12.%"
+PREFERRED_VERSION_nodejs-native ?= "14.%" 

We were hoping that the native version of nodejs would not matter but, unfortunately, bitbake nodejs(12) fails with the error:
../../deps/v8/src/builtins/array-join.tq:151:8: Torque Error: Parser Error: unexpected token "("

This above error comes from the torque executable running on this tq file. It appears like syntax changed between version 12 and 14. :-(

We are trying not to change nodejs_12 behavior while making nodejs-native_14 available to chromium. Chromium recipe is used in many branches so, without making a branch in meta-browser for dunfell, we don't see how to introduce a dependency on nodejs-native_14 using either a PREFERRED_VERSION or by calling the recipe nodejs-14-native since, that will force all branches to use nodejs-14-native even if they are not using the dunfell branch.

Is there a way to achieve this goal without introducing a branch in meta-browser for dunfell ?

As a test, we have added PREFERRED_VERSION_nodejs-native = "14.%" to conf/local.conf and built bitbake chromium-x11.
That picks up nodejs-native_14 as expected and build will take sometime to complete.

Other solution is that we would required to add PREFERRED_VERSION_nodejs-native = "14.%" to conf/local.conf file while building the chromium for dunfell.
More to come tomorrow...

2023-05-10 08:04 UTC, ekapllaj commented
Hi, I actually would prefer the creation of a branch for dunfell. The dunfell distro is going to be around at least until next year (Apr 2024), and I think this issue is comming to bite as at every update. I'm building on Honister and chromium 113 is not compiling at all, so I think it's going to be complicated to try to compile for dunfell for next releases.

I would say that the best compromise would be to kind of freeze the chromium 112 on a separate branch for dunfell (with the appropriate patches) and move on on master branch.

2023-05-10 10:09 UTC, otavio commented
If we choose the dunfell branch, we can branch out on 111 and implement the necessary build fixes. I'm okay with that, but everyone needs to understand that no security updates will be applied.

2023-05-10 10:12 UTC, rakuco commented
I'm in the "those who do the work decide" camp. I've been happily reviewing pull requests but haven't worked on updates myself for a while. If the people who have been carrying out the work like @MaxIhlenfeldt, @rwmacleod and @nrpt-m feel like it's no longer worth supporting dunfell (due to either the maintenance burden or lack of client demand), I certainly have no objections.

dunfell users might not be very happy, but it would certainly make updates a lot easier for us.

2023-05-16 14:47 UTC, otavio commented
Are you looking to include a note regarding the usage of the `dunfell` branch that mentions its restriction?

2023-05-16 14:59 UTC, nrpt-m commented
> Are you looking to include a note regarding the usage of the `dunfell` branch that mentions its restriction?

@otavio Have already added the set-up requirements when on dunfell in the PR & commit messages.

2023-05-16 15:01 UTC, kraj commented
Patch to add nodejs 14 has landed in `meta-openembedded/dunfell` 
https://git.openembedded.org/meta-openembedded/commit/?h=dunfell&id=116bfe8d5e5851e7fc5424f40da8691a19c5b5ee

2023-05-17 14:41 UTC, rwmacleod commented
Looks like we're finally good to go. @MaxIhlenfeldt  @rafluan @kraj please merge if you agree.

2023-05-17 15:00 UTC, MaxIhlenfeldt requested changes
Thanks a lot for finishing this! Almost LGTM, just some polishing comments.

Can you please remove the mentions of `0017-Revert-WebUI-Update-Rollup-to-v3.12.0.patch` and `0019-Backport-Fix-deps-for-feed_response.proto.patch` from the PR description? Not sure if it makes sense to also squash the commits, so that the new single commit message matches the description?

2023-05-17 15:20 UTC, kraj commented
@nrpt-m Can you address these comments and upload again

2023-05-17 15:44 UTC, nrpt-m commented on meta-chromium/recipes-browser/chromium/files/0020-Only-default-operator-on-declaration.patch
Done.

2023-05-17 15:46 UTC, nrpt-m commented
> Thanks a lot for finishing this! Almost LGTM, just some polishing comments.
> 
> Can you please remove the mentions of `0017-Revert-WebUI-Update-Rollup-to-v3.12.0.patch` and `0019-Backport-Fix-deps-for-feed_response.proto.patch` from the PR description? Not sure if it makes sense to also squash the commits, so that the new single commit message matches the description?

Have removed the mentions of `0017-Revert-WebUI-Update-Rollup-to-v3.12.0.patch` and `0019-Backport-Fix-deps-for-feed_response.proto.patch` from the PR description but, kept as it is in commit message.

2023-05-17 15:49 UTC, nrpt-m commented
> @nrpt-m Can you address these comments and upload again

Done.
Shall I move "fix-libc-version-include.patch" patch into musl/ as @MaxIhlenfeldt suggested ?

2023-05-17 16:20 UTC, kraj commented
> > @nrpt-m Can you address these comments and upload again
> 
> Done. Shall I move "fix-libc-version-include.patch" patch into musl/ as @MaxIhlenfeldt suggested ?

yes

2023-05-17 17:13 UTC, nrpt-m commented
@MaxIhlenfeldt , @kraj 
Requested changes has been done and let me know if any further modification needed.

2023-05-17 17:13 UTC, kraj approved these changes

2023-05-17 17:20 UTC, rakuco approved these changes
lgtm too. Thank you very much everyone who contributed to this work, this update has been one of the tough ones but this version looks a lot better and I'm sure that having nodejs 14 in dunfell will make our lives easier in the future!

2023-05-17 17:20 UTC, rakuco commented on meta-chromium/recipes-browser/chromium/files/0013-Fix-html_minifier-script-for-node-v12.patch
>   1 file changed, 1 insertion(+), 1 deletion(-)
Not necessarily in this PR, I think we can get rid of this patch now that we're requiring nodejs >= 14 on all branches.

2023-05-17 17:25 UTC, nrpt-m commented on meta-chromium/recipes-browser/chromium/files/0013-Fix-html_minifier-script-for-node-v12.patch
>   1 file changed, 1 insertion(+), 1 deletion(-)
Shall I remove this patch as well if you think it's not needed anymore ?

2023-05-17 17:38 UTC, rakuco commented on meta-chromium/recipes-browser/chromium/files/0013-Fix-html_minifier-script-for-node-v12.patch
>   1 file changed, 1 insertion(+), 1 deletion(-)
If you have enough cycles to test it, then yes, otherwise it can be done in another PR.

2023-05-17 17:56 UTC, rwmacleod commented on meta-chromium/recipes-browser/chromium/files/0013-Fix-html_minifier-script-for-node-v12.patch
>   1 file changed, 1 insertion(+), 1 deletion(-)
I vote for dropping that patch in 113.

2023-05-17 17:57 UTC, nrpt-m commented on meta-chromium/recipes-browser/chromium/files/0013-Fix-html_minifier-script-for-node-v12.patch
>   1 file changed, 1 insertion(+), 1 deletion(-)
Let's do it in 113 ;-)

2023-05-18 08:41 UTC, MaxIhlenfeldt approved these changes
LGTM, thanks!

2023-05-18 08:42 UTC, merged